<a href="https://colab.research.google.com/github/Saniyashaikh1505/Machine-Learning-Projects/blob/main/Feature_Engineering_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Steps in Feature Engineering**

Step 1- Data Cleaning - Handling missing values, handling outliers and handling inconsistencies

Step 2 - Feature Transformation (Feature Encoding and Feature Scaling)
        -> Feature Encoding (Label Encoding, One-Hot Encoding, Freaquncy Encoding, Target Encoding)
        -> Feature Scaling (Normalization , Standarization)

Step 3 - Feature Extraction

Step 4 - Feature Selection

In [24]:
import pandas as pd
import numpy as np

In [25]:
dataset = pd.read_csv('/content/drive/MyDrive/Data Analysis Portfolio - Saniya Shaikh/Machine Learning Projects - Python/Python Data File/employee_promotion.csv')
dataset.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Promotion
0,28,132612,9,2,1,Data Engineer,High School,Seattle,Got Promotion
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,No Promotion
2,36,113811,11,1,6,Web developer,PhD,Chicago,Got Promotion
3,32,102160,2,2,6,Data Engineer,High School,Austin,No Promotion
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,No Promotion

## **Feature Encoding**

In [26]:
from sklearn.preprocessing import LabelEncoder

df= dataset.copy()

LabelEncoder = LabelEncoder()
df['Promotion_Encoded'] = LabelEncoder.fit_transform(df['Promotion'])
df.head()

df['Education'].unique()

array(['High School', "Master's", 'PhD', "Bachelor's"], dtype=object)

In [27]:
# Label Encoding with order - Education
Education_dict = {'High School' : 0, "Bachelor's" : 1, "Master's" : 2, "PhD" : 3}
df['Education_Encoded']= df['Education'].map(Education_dict)
df.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Promotion,Promotion_Encoded,Education_Encoded
0,28,132612,9,2,1,Data Engineer,High School,Seattle,Got Promotion,0,0
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,No Promotion,1,2
2,36,113811,11,1,6,Web developer,PhD,Chicago,Got Promotion,0,3
3,32,102160,2,2,6,Data Engineer,High School,Austin,No Promotion,1,0
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,No Promotion,1,1

In [28]:
#One-Hot Encoding - City
df_encoded = pd.get_dummies(df, columns=['City'])
df_encoded.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,Promotion,Promotion_Encoded,Education_Encoded,City_Austin,City_Chicago,City_New York,City_San Francisco,City_Seattle
0,28,132612,9,2,1,Data Engineer,High School,Got Promotion,0,0,False,False,False,False,True
1,41,116641,8,4,3,Data Scientist,Master's,No Promotion,1,2,False,True,False,False,False
2,36,113811,11,1,6,Web developer,PhD,Got Promotion,0,3,False,True,False,False,False
3,32,102160,2,2,6,Data Engineer,High School,No Promotion,1,0,True,False,False,False,False
4,29,101313,7,4,7,Product Manager,Bachelor's,No Promotion,1,1,False,False,False,True,False

In [29]:
#Frequency Encoding - Job Title
job_title_counts = df['JobTitle'].value_counts()
df['JobTitle_Encoded'] = df['JobTitle'].map(job_title_counts)
df.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Promotion,Promotion_Encoded,Education_Encoded,JobTitle_Encoded
0,28,132612,9,2,1,Data Engineer,High School,Seattle,Got Promotion,0,0,699
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,No Promotion,1,2,705
2,36,113811,11,1,6,Web developer,PhD,Chicago,Got Promotion,0,3,733
3,32,102160,2,2,6,Data Engineer,High School,Austin,No Promotion,1,0,699
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,No Promotion,1,1,750

# **Feature Scaling**

In [30]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

df_scale = dataset.copy()

#Standard Scaler
standard_scaler = StandardScaler()
df_scale['Standard_Salary'] = standard_scaler.fit_transform(df_scale[['Salary']])

#Min-Max Scaler
min_max_scaler = MinMaxScaler()
df_scale['Min_Max_Salary'] = min_max_scaler.fit_transform(df_scale[['Salary']])

df_scale.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Promotion,Standard_Salary,Min_Max_Salary
0,28,132612,9,2,1,Data Engineer,High School,Seattle,Got Promotion,1.120060,0.826129
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,No Promotion,0.572455,0.666363
2,36,113811,11,1,6,Web developer,PhD,Chicago,Got Promotion,0.475421,0.638053
3,32,102160,2,2,6,Data Engineer,High School,Austin,No Promotion,0.075938,0.521503
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,No Promotion,0.046897,0.513030

# **Feature Extraction**

In [31]:
data_cust = pd.read_csv('/content/drive/MyDrive/Data Analysis Portfolio - Saniya Shaikh/Machine Learning Projects - Python/Python Data File/retail_customer.csv')
data_cust.head()

,customer_id,name,age,gender,signup_date,last_purchase_date,total_purchases,total_spent,country,email,device_type,is_subscribed,feedback_score
0,5c7825f3-13bb-4843-9cf1-5b7a944def13,Andrew Miller,56,Male,2025-01-01,2024-06-12,18,6143.01,Bangladesh,qwilson@example.org,Mobile,1,2.7
1,ad1cf2e3-be49-4031-9770-c308b2d1292c,Kevin Ramos,69,Other,2025-05-16,2024-10-03,86,9498.14,Eritrea,shall@example.net,Mobile,1,1.6
2,33194def-ebb0-4d75-8942-9c83d7d579f2,John Smith,46,Other,2025-04-15,2025-04-27,34,4026.83,Russian Federation,leebrian@example.org,Mobile,0,3.7
3,6a1ce340-ec27-482e-a339-e89e2db11a01,Dustin Nolan,32,Male,2023-10-10,2024-10-20,8,9545.46,Serbia,sguzman@example.org,Mobile,1,1.9
4,3e529d86-76ed-4c85-83cf-c5ab446cb3c0,Amy Johnson,60,Female,2024-02-02,2025-03-03,40,1436.51,Mauritius,griffithsarah@example.org,Mobile,1,1.4

In [32]:
#binning age into categories
bins = [10,30,50,70] #Age ranges
labels = ['Young','Mid','Senior']
data_cust['age_group']=pd.cut(data_cust['age'],bins = bins,labels = labels)
data_cust[['age','age_group']].head(20)

    age age_group
0    56    Senior
1    69    Senior
2    46       Mid
3    32       Mid
4    60    Senior
5    25     Young
6    38       Mid
7    56    Senior
8    36       Mid
9    40       Mid
10   28     Young
11   28     Young
12   41       Mid
13   53    Senior
14   57    Senior
15   41       Mid
16   20     Young
17   39       Mid
18   19     Young
19   41       Mid

In [33]:
#converting date column to datetime
data_cust['Signup_date']=pd.to_datetime(data_cust['signup_date'])
data_cust['last_purchase_date']=pd.to_datetime(data_cust['last_purchase_date'])
data_cust.dtypes

customer_id                   object
name                          object
age                            int64
gender                        object
signup_date                   object
last_purchase_date    datetime64[ns]
total_purchases                int64
total_spent                  float64
country                       object
email                         object
device_type                   object
is_subscribed                  int64
feedback_score               float64
age_group                   category
Signup_date           datetime64[ns]
dtype: object